name: Run ES Lint

on:
    push:
    pull_request_target:
        types: [assigned, opened, synchronize, reopened]

env:
    DISABLE_PROGRESS: true

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    RunLint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  token: "${{ secrets.ES_LINT_TOKEN }}"
                  ref: ${{github.event.pull_request.head.sha}}
                  repository: ${{github.event.pull_request.head.repo.full_name}}

            - name: Node.JS 18
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Install Node Dependencies
              run: npm ci
              env:
                  CI: TRUE

            - name: Lint Report
              # This is to show the failures in Github actions
              run: npm run lint
              continue-on-error: true
