name: JIRA
run-name: Link JIRA to ${{ github.event.pull_request.head.ref || github.event.pull_request.number }}

on:
    pull_request:
        types: [opened, reopened]

permissions:
    contents: read
    pull-requests: write

jobs:
    link-jira:
        name: Link to PR
        uses: xola/actions/.github/workflows/link-jira.yml@main
        secrets: inherit
